# Generated by Django 4.1.7 on 2023-05-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2002-05-17'),
            preserve_default=False,
        ),
    ]
